sensor:
  - platform: pulse_counter
    id: "${pulse_counter_id_prefix}04"
    name: "{fan_name_prefix}04${pulse_counter_name_suffix}"
    icon: ${pulse_counter_icon}
    pin: 
      number: GPIO07
      mode: INPUT_PULLUP
    unit_of_measurement: ${pulse_counter_unit}
    accuracy_decimals: 0
    filters:
      - multiply: ${pulse_counter_factor}
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: ${pulse_counter_interval}

fan:
  - platform: speed
    id: "${fan_control_id_prefix}04"
    name: "{fan_name_prefix}04${pwm_name_suffix}"
    icon: ${pwm_icon}
    output: "${pwm_id_prefix}04"
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: ledc
    id: "${pwm_id_prefix}04"
    channel: 6
    pin: GPIO06
    frequency: ${pwm_frequency}