sensor:
  - platform: pulse_counter
    id: fan_tacho_02
    name: "Fan 02 - Speed"
    icon: ${pulse_counter_icon}
    pin: 
      number: GPIO10
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    filters:
      - multiply: 0.5
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: ${pulse_counter_interval}

fan:
  - platform: speed
    id: fan_control_02
    name: "Fan 02 - ${pwm_name_suffix}"
    icon: ${pwm_icon}
    output: fan_pwm_02
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: ledc
    id: "${pwm_id_prefix}02"
    channel: 2
    pin: GPIO11
    frequency: ${pwm_frequency}