sensor:
  - platform: pulse_counter
    id: fan_tacho_03
    name: "Fan 03 - Speed"
    icon: ${pulse_counter_icon}
    pin: 
      number: GPIO09
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    filters:
      - multiply: 0.5
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: ${pulse_counter_interval}

fan:
  - platform: speed
    id: fan_control_03
    name: "Fan 03 - ${pwm_name_suffix}"
    icon: ${pwm_icon}
    output: fan_pwm_03
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: ledc
    id: fan_pwm_03
    channel: 4
    pin: GPIO08
    frequency: ${pwm_frequency}