sensor:
  - platform: pulse_counter
    id: fan_tacho_04
    name: "Fan 04 - Speed"
    icon: ${pulse_counter_icon}
    pin: 
      number: GPIO07
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    filters:
      - multiply: 0.5
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: ${pulse_counter_interval}

fan:
  - platform: speed
    id: fan_control_04
    name: "Fan 04 - ${pwm_name_suffix}"
    icon: ${pwm_icon}
    output: fan_pwm_04
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: ledc
    id: "${pwm_id_prefix}04"
    channel: 6
    pin: GPIO06
    frequency: ${pwm_frequency}