# Example Usage:
#
#substitutions:
#  device_site: "bl24"
#  device_location_code: "caracal"
#  device_location_name: "Caracal"
#  device_number: "160"
#  device_ip: "10.16.40.85"
#
#packages:
#  base_package:
#    url: https://github.com/mariodivece/esphometemplates/
#    ref: main
#    file: afc-v1.yaml
#    refresh: 0d


substitutions:
  # User-required substitutions
  device_site: "bl24"
  device_location_code: "caracal"
  device_location_name: "Caracal"
  device_type_code: "afc1"
  device_type_name: "Advanced Fan Controller"
  device_number: "160"
  device_ip: "10.16.16.101"

  # Project Substitutions (not intended for user substitution)
  device_model: "AFC V1"
  device_make: "Bullet Automation"
  package_version: "2024.11.24"
  package_url: "github://mariodivece/esphometemplates/afc-v1.yaml@main"

  log_level: INFO

  # GPIO Configurations
  fan_name_prefix: "Fan "
  fan_control_id_prefix: "fan_control_"
  pulse_counter_icon: 'mdi:speedometer'
  pulse_counter_interval: 2s
  pulse_counter_id_prefix: 'fan_tacho_'
  pulse_counter_name_suffix: ' - Speed'
  pulse_counter_factor: 0.5
  pulse_counter_unit: 'RPM'
  pwm_frequency: 25000Hz
  pwm_icon: 'mdi:fan'
  pwm_name_suffix: ' - Control'
  pwm_id_prefix: 'fan_pwm_'

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - afc-v1/board-esp32s3zero.yaml
      - standard/project.yaml
      - standard/diagnostics.yaml
      - standard/wifi.yaml
      - standard/internaltemp.yaml
      - afc-v1/webserver.yaml
      - afc-v1/onboard-rgbled.yaml
      - afc-v1/bmp280.yaml
      - afc-v1/pwmfan-01.yaml
      - afc-v1/pwmfan-02.yaml
      - afc-v1/pwmfan-03.yaml
      - afc-v1/pwmfan-04.yaml
