# Example Usage:
#
#substitutions:
#  device_site: "bl24"
#  device_location_code: "caracal"
#  device_location_name: "Caracal"
#  device_number: "160"
#  device_ip: "10.16.40.85"
#  fan_label_01: "Front Grill"
#  fan_label_02: "PCIe Blower"
#  fan_label_03: "(Not Connected)"
#  fan_label_04: "Exhaust"
#  ambient_sensor_label: "Ambient Sensor (BMP280)"
#
#packages:
#  base_package:
#    url: https://github.com/mariodivece/esphometemplates/
#    ref: main
#    file: afc-xiao-s3.yaml
#    refresh: 0d

substitutions:
  # User-required substitutions
  device_site: "bl24"
  device_location_code: "caracal"
  device_location_name: "Caracal"
  device_type_code: "afc2"
  device_type_name: "Advanced Fan Controller"
  device_number: "110"
  device_ip: "10.16.16.110"

  # Auto controller Tuning
  temp_low: '30.0'
  temp_high: '36.0'
  speed_low: '5.0'
  speed_high: '35.0'
  pwm_min_power: '0.05'

  # Project Substitutions (not intended for user substitution)
  device_model: "AFC X3"
  device_make: "Bullet Automation"
  package_version: "2024.12.15"
  package_url: "github://mariodivece/esphometemplates/afc-xiao-s3.yaml@main"

  log_level: INFO

  # GPIO Configurations -- Not intended for user substitutions
  i2c_scl: 'GPIO06'
  i2c_sda: 'GPIO05'
  fan_01_i_pin: 'GPIO44'
  fan_01_o_pin: 'GPIO07'
  fan_02_i_pin: 'GPIO08'
  fan_02_o_pin: 'GPIO09'
  fan_03_i_pin: 'GPIO43'
  fan_03_o_pin: 'GPIO04'
  fan_04_i_pin: 'GPIO01'
  fan_04_o_pin: 'GPIO02'

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - afc/board-xiao-s3.yaml
      - afc/subs-generic.yaml
      - standard/diagnostics.yaml
      - standard/wifi.yaml
      - afc/webserver.yaml
      #- afc/onboard-rgbled.yaml
      - afc/sensor-bmp280.yaml
      - afc/pwmfan-01.yaml
      - afc/pwmfan-02.yaml
      - afc/pwmfan-03.yaml
      - afc/pwmfan-04.yaml
      - afc/controller.yaml
      