# Example Usage:
#
#substitutions:
#  device_site: "bl24"
#  device_location_code: "caracal"
#  device_location_name: "Caracal"
#  device_number: "160"
#  device_ip: "10.16.40.85"
#  fan_label_01: "Front Grill"
#  fan_label_02: "PCIe Blower"
#  fan_label_03: "(Not Connected)"
#  fan_label_04: "Exhaust"
#  ambient_sensor_label: "Ambient Sensor (BMP280)"
#
#packages:
#  base_package:
#    url: https://github.com/mariodivece/esphometemplates/
#    ref: main
#    file: afc-v4.yaml
#    refresh: 0d

substitutions:
  # User-required substitutions
  device_site: "bl24"
  device_location_code: "caracal"
  device_location_name: "Caracal"
  device_number: "200"
  device_ip: "192.168.44.200"

  # Project Substitutions (not intended for user substitution)
  device_type_code: "afc4"
  device_type_name: "AFC"
  device_model: "AFC v4"
  device_make: "Bullet Automation"
  package_version: "2024.12.27"
  package_url: "github://mariodivece/esphometemplates/afc-v4.yaml@main"

  log_level: INFO

  # GPIO Configurations -- Not intended for user substitutions
  i2c_scl: 'GPIO06'
  i2c_sda: 'GPIO05'
  fan_01_i_pin: 'GPIO44'
  fan_01_o_pin: 'GPIO07'
  fan_02_i_pin: 'GPIO08'
  fan_02_o_pin: 'GPIO09'
  fan_03_i_pin: 'GPIO43'
  fan_03_o_pin: 'GPIO04'
  fan_04_i_pin: 'GPIO01'
  fan_04_o_pin: 'GPIO02'

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - afc-v4/board-xiao-s3.yaml
      - afc-v4/subs-generic.yaml
      - standard/diagnostics.yaml
      - standard/wifi.yaml
      - afc-v4/webserver.yaml
      - afc-v4/sensor-bmp280.yaml
      - afc-v4/pwmfan-01.yaml
      - afc-v4/pwmfan-02.yaml
      - afc-v4/pwmfan-03.yaml
      - afc-v4/pwmfan-04.yaml
      - afc-v4/controller.yaml
      