substitutions:
  # User-required substitutions
  device_site: "bl24"
  device_location_code: "caracal"
  device_location_name: "Caracal"
  device_type_code: "afc1"
  device_type_name: "Advanced Fan Controller"
  device_number: "160"
  device_ip: "10.16.16.101"

  # Project Substitutions (not intended for user substitution)
  device_model: "AFC V1"
  device_make: "Bullet Automation"
  package_version: "2024.11.24"
  package_url: "github://mariodivece/esphometemplates/afc-v1.yaml@main"

  log_level: INFO

# Allow importing this package
dashboard_import:
  package_import_url: ${package_url}
  import_full_config: false

# Enable Web Server Control
web_server:
  port: 80
  version: 3

# Import packages
packages:
  standard_package:
    url: https://github.com/mariodivece/esphometemplates/
    ref: main
    refresh: 0d
    files:
      - afc-v1/board-esp32s3zero.yaml
      - standard/project.yaml
      - standard/diagnostics.yaml
      - standard/wifi.yaml
      - standard/internaltemp.yaml
      - afc-v1/onboard-rgbled.yaml
      - peripherals/bmp280.yaml
      - afc-v1/pwmfan-01.yaml
      - afc-v1/pwmfan-02.yaml
      - afc-v1/pwmfan-03.yaml
      - afc-v1/pwmfan-04.yaml
